modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "shadowedhearts"
version = "${version}"
displayName = "Cobblemon: Shadowed Hearts"
authors = "JayemCeekay"
description = '''

'''
logoFile = "assets/shadowedhearts/icon.png"

[[dependencies.shadowedhearts]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shadowedhearts]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shadowedhearts]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.shadowedhearts]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.shadowedhearts]]
modId = "rctapi"
type = "optional"
versionRange = "[0.14.4-beta,)"
side = "BOTH"

[[mixins]]
config = "shadowedhearts.mixins.json"
